version: 0.2

phases:
  install:
    commands:
      - sudo apt install libssl1.0-dev
      - sudo apt install nodejs-dev
      - sudo apt install node-gyp
      - sudo apt install npm

  pre_build:
    commands:
      # install dependencies
      - echo Installing deopendencies...
      - npm install
  build:
    commands:
      - echo Building...
      - npm build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
